/* eslint-disable @next/next/no-page-custom-font */
import type { Metadata } from "next";
import TopBar from "@/components/organisms/top-bar";
import { ThemeProvider } from "@/components/providers/theme-provider";
import "../globals.css";
import Typography from "@/components/atoms/typography";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <head>
        <link rel="preconnect" href="https://fonts.googleapis.com" />
        <link
          rel="preconnect"
          href="https://fonts.gstatic.com"
          crossOrigin="anonymous"
        />
        <link
          href="https://fonts.googleapis.com/css2?family=Boogaloo&family=Nunito+Sans:ital,opsz,wght@0,6..12,200..1000;1,6..12,200..1000&display=swap"
          rel="stylesheet"
        ></link>
      </head>
      <body className="flex flex-col pt-[1rem] md:pt-6 bg-background min-h-screen">
        <ThemeProvider
          attribute="class"
          defaultTheme="system"
          enableSystem
          disableTransitionOnChange
        >
          <TopBar />

          {children}

          <footer className="flex gap-6 flex-wrap items-center justify-center p-4 mt-24 border-t w-full">
            <Typography as="p" size={"xxs"} className="text-center font-thin">
              © 2026 by Lingualoomm. Powered and secured by Lingualoomm
            </Typography>
          </footer>
        </ThemeProvider>
      </body>
    </html>
  );
}
